version: '3.8'

services:

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: users
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
